inherit: true

tools:
    external_code_coverage:
        timeout: 900
    php_code_coverage: false
    php_code_sniffer: true
    php_cpd: true
    php_cs_fixer: true
    php_loc: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true